// let aa = '<div id="aaaa">aaa</div>';

let pdTable = '<table class="pdTable">'
        +'<thead>'
            +'<tr><th>環抱適安撫床租用辦法</th><th>電動型</th><th>親子型(手搖款)</th></tr>'
        +'</thead>'
        // +'<tbody>'
            +'<tr>'
            +'<td>租期最少3個月<br>租期未滿皆以3個月計</td>'
                +'<td>1200<br>平均400/月</td>'
                +'<td>600<br>平均200/月</td>'
            +'</tr>'
            +'<tr>'
                +'<td>須購買全新白吊床<br>(毋須歸還也不退貨)</td>'
                +'<td>1200</td>'
                +'<td>1200</td>'
            +'</tr>'
            +'<tr>'
                +'<td>來回運費 (限台灣)</td>'
                +'<td>400</td>'
                +'<td>400</td>'
                
                +'</tr>'
            +'<tr>'
                +'<td>租用押金</td>'
                +'<td>4100</td>'
                +'<td>1500</td>'
                
            +'</tr>'
            +'<tr>'
                +'<td></td><td></td><td></td>'
                    
                +'</tr>'
            +'<tr>'
                +'<td>匯款金額合計</td>'
                +'<td>6900</td>'
                +'<td>3700</td>'
            +'</tr>'
        // +'</tbody>'
    +'</table>'